[control_plane]
pi-node1 ansible_host=10.100.102.10

[workers]
pi-node2 ansible_host=10.100.102.16
pi-node3 ansible_host=10.100.102.17
pi-node4 ansible_host=10.100.102.12

[k3s_cluster:children]
control_plane
workers

[platform]
pi-node1 ansible_host=10.100.102.10
