apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pi-cluster.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-cluster-redis
  template:
    metadata:
      labels:
        app: pi-cluster-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: {{ .Values.redis.port }}
          command:
            - redis-server
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pi-cluster-secrets
                  key: REDIS_PASSWORD
